

# Setup
title:            Haikal Fouzi
tagline:
description:      "Haikal Fouzi's research"
url:              http://haikalfouzi.com
baseurl:          /

author:
  name:           'Haikal Fouzi'
  url:            https://twitter.com/trndbtd

paginate:         100

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/haikalfouzi
